name: Build and Deploy to Firebase

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install root dependencies
      run: npm install

    - name: Install UI dependencies
      run: |
        cd ui
        npm install

    - name: Install Server dependencies
      run: |
        cd server
        npm install

    - name: Build UI
      run: |
        cd ui
        npm run build

    - name: Build Server
      run: |
        cd server
        npm run build

    - name: Deploy to Firebase Hosting
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}'
        projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'
        channelId: live

    - name: Deploy to Firebase Preview
      if: github.event_name == 'pull_request'
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}'
        projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'
